name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./cleantask/pom.xml
          mvn clean package -f ./reservation/pom.xml
          mvn clean package -f ./lostitem/pom.xml
          mvn clean package -f ./confirm/pom.xml

      - name: Docker Build and push for Cleantask
        uses: docker/build-push-action@v4
        with:
          context: ./cleantask
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cleantask:latest
            ghcr.io/${{ github.repository }}/cleantask:${{ github.ref_name }}
            
      - name: Docker Build and push for Reservation
        uses: docker/build-push-action@v4
        with:
          context: ./reservation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservation:latest
            ghcr.io/${{ github.repository }}/reservation:${{ github.ref_name }}
            
      - name: Docker Build and push for Lostitem
        uses: docker/build-push-action@v4
        with:
          context: ./lostitem
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/lostitem:latest
            ghcr.io/${{ github.repository }}/lostitem:${{ github.ref_name }}
            
      - name: Docker Build and push for Confirm
        uses: docker/build-push-action@v4
        with:
          context: ./confirm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/confirm:latest
            ghcr.io/${{ github.repository }}/confirm:${{ github.ref_name }}
            
