apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostitem
  labels:
    app: lostitem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostitem
  template:
    metadata:
      labels:
        app: lostitem
    spec:
      containers:
        - name: lostitem
          image: "username/lostitem:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
