server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: cleantask
          uri: http://localhost:8082
          predicates:
            - Path=/cleanTasks/**, 
        - id: reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/**, 
        - id: lostitem
          uri: http://localhost:8084
          predicates:
            - Path=/lostItems/**, 
        - id: confirm
          uri: http://localhost:8085
          predicates:
            - Path=/confirms/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: cleantask
          uri: http://cleantask:8080
          predicates:
            - Path=/cleanTasks/**, 
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**, 
        - id: lostitem
          uri: http://lostitem:8080
          predicates:
            - Path=/lostItems/**, 
        - id: confirm
          uri: http://confirm:8080
          predicates:
            - Path=/confirms/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
