---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleantask
  labels:
    app: cleantask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleantask
  template:
    metadata:
      labels:
        app: cleantask
    spec:
      containers:
        - name: cleantask
          image: username/cleantask:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: username/reservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostitem
  labels:
    app: lostitem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostitem
  template:
    metadata:
      labels:
        app: lostitem
    spec:
      containers:
        - name: lostitem
          image: username/lostitem:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: confirm
  labels:
    app: confirm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confirm
  template:
    metadata:
      labels:
        app: confirm
    spec:
      containers:
        - name: confirm
          image: username/confirm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: cleantask
  labels:
    app: cleantask
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cleantask


---


apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservation


---


apiVersion: v1
kind: Service
metadata:
  name: lostitem
  labels:
    app: lostitem
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lostitem


---


apiVersion: v1
kind: Service
metadata:
  name: confirm
  labels:
    app: confirm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: confirm

